# Generated by Django 4.2.4 on 2023-09-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectingToKIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(help_text='Input your DataBase name', max_length=20)),
                ('host', models.CharField(help_text='Input your host name', max_length=30)),
                ('port', models.CharField(help_text='Input your port', max_length=10)),
                ('user', models.CharField(help_text='Input DB username', max_length=20)),
                ('password', models.CharField(help_text='Input your DataBase pass', max_length=20)),
            ],
        ),
    ]
